In [3]:
! export JAX_PLATFORMS=cpu

/gpfs/cfel/group/cmi/common/psi4/psi4conda/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


# Rotational-vibrational solutions for H2S molecule

Compute rovibrational energies, wavefunctions, and matrix elements for H2S, up to high rotational excitations ($J\sim 60$) at which rotational cluster states are formed.

In [4]:
import jax
import numpy as np
from jax import config
from jax import numpy as jnp
from numpy.polynomial.hermite import hermgauss
from scipy import optimize

from rovib.h2s_potential import potential
from rovib.h2s_spinrot import spinrot_const_bisector
from rovib.keo import Molecule, batch_Gmat, batch_pseudo, com
from rovib.primbas import hermite
from rovib.symtop import rotme_cor, rotme_ovlp, rotme_rot
from rovib.vib_xy2 import vibrations_xy2
from rovib import c2v

config.update("jax_enable_x64", True)

## Vibrational coordinates and molecular frame

Define atomic masses and internal coordinates for describing vibrations. Here, we use the valence-bond coordinates, $r_1\equiv \text{S--H}_1$, $r_2\equiv \text{S--H}_2$, and $\alpha = \angle\text{H}_1\text{SH}_2$. The function `valence_bond_coordinates` is required to build the kinetic energy operator.

In [6]:
NCOO = 3 # number of vibrational coordinates
MASS_S = 31.97207070
MASS_H = 1.00782505

@com
def valence_bond_coordinates(coords):
    r1, r2, alpha = coords
    return jnp.array(
        [
            [0.0, 0.0, 0.0],
            [r1 * jnp.cos(alpha / 2), 0.0, r1 * jnp.sin(alpha / 2)],
            [r2 * jnp.cos(alpha / 2), 0.0, -r2 * jnp.sin(alpha / 2)],
        ]
    )

Molecule.masses = np.array([MASS_S, MASS_H, MASS_H])
Molecule.internal_to_cartesian = valence_bond_coordinates

We use Hermite functions $H_n(x)e^{-x^2/2}$ as the vibrational basis functions and employ Gauss-Hermite quadratures for computing matrix elements.

The Hermite functions are defined over the coordinate range $x\in(-\infty,\infty)$. To map $x$ into the vibrational valence bond coordinates $r_1\in(0,\infty)$, $r_2\in(0,\infty)$, and $\alpha=(0,\pi)$,
we use linear transformations $r_1=a_1x_1+b_1$, $r_2=a_2x_2+b_2$, $\alpha=a_3x_3+b_3$.
The parameters $a_1, b_1, ..., b_3$ are determined by mapping the vibrational Hamiltonian in valence-bond coordinates onto the harmonic oscillator Hamiltonian.

In [7]:
vmin = optimize.minimize(potential, [1.0, 1.0, np.pi / 2])
r0 = vmin.x
v0 = vmin.fun
print("mininum of the potential:", r0, v0)

freq = jnp.diag(jax.hessian(potential)(r0))
mu = jnp.diag(batch_Gmat(jnp.array([r0]))[0, :NCOO, :NCOO])
lin_a = jnp.sqrt(jnp.sqrt(mu / freq))
lin_b = r0

print("x->r linear mapping parameters 'a' and 'b':", lin_a, lin_b)

# x->r linear mapping function
x_to_r_map = lambda x: lin_a * x + lin_b

mininum of the potential: [1.3358387  1.3358387  1.61042427] -0.0007846164037194908
x->r linear mapping parameters 'a' and 'b': [0.11245619 0.11245619 0.17845517] [1.3358387  1.3358387  1.61042427]


We will be computing rovibrational matrix elements of spin-rotation tensors, which were obtained in a quantum chemical calculation in some reference coordinate frame. This frame may be different from the one used here as defined by the `valence_bond_coordinates` function. Therefore, the spin-rotation tensors need to be rotated to the same coordinate frame as used here for rovibrational solutions.

Such frame transformation is already coded in the module `rovib.h2s_spinrot` and here we check that Cartesian coordinates of atoms after the transformation match those returned by the `valence_bond_coordinates` function.

In [12]:
from rovib.h2s_spinrot import _COORDS

print("Reference internal coordiantes:", _COORDS)

sr, atom_xyz0 = spinrot_const_bisector(np.array([_COORDS]), return_atom_xyz=True)
sr1 = sr[:, 0]
sr2 = sr[:, 1]
print("Reference Cartesian coordinates of atoms:\n", atom_xyz0)

atom_xyz = valence_bond_coordinates(_COORDS)
print("Calculated from internal Cartesian coordinates of atoms:\n", atom_xyz)

print("max difference:", np.max(np.abs(atom_xyz0 - atom_xyz), axis=-1))

Reference internal coordiantes: [1.35, 1.35, 1.605702911834783]
Reference Cartesian coordinates of atoms:
 [[-0.05561581  0.          0.        ]
 [ 0.88217319  0.          0.97110893]
 [ 0.88217319  0.         -0.97110893]]
Calculated from internal Cartesian coordinates of atoms:
 [[-5.56157943e-02  0.00000000e+00 -1.41018406e-18]
 [ 8.82173006e-01  0.00000000e+00  9.71108730e-01]
 [ 8.82173006e-01  0.00000000e+00 -9.71108730e-01]]
max difference: [1.08848569e-08 2.02253066e-07 2.02253066e-07]


## Vibrational basis set contraction

To optimize the vibrational basis set, we begin by solving a simplified vibrational problem for each individual vibrational coordinate.
For this, we set the basis functions for all coordinates to $e^{−x^2/2}$ except for one.
We then use the corresponding solutions obtained sequentially for each coordinate to construct a contracted product basis set.

In [13]:
# list of 1D primitive basis functions for each vibrational coordinate
list_psi = (hermite, hermite, hermite)

# number of primitive basis functions for each vibrational coordinate
nmax = 40

# number of quadrature points for each vibrational coordinate
npoints = 80

contr_vec = []

for icoo in range(NCOO):
    print(f"\nSolve for coordinate #{icoo}")

    # quanta, set quanta to zero for all coordinates except the `icoo`
    list_q = [np.arange(nmax) if i == icoo else [0] for i in range(NCOO)]

    # quadratures, reduce number of points for all coordinates except the `icoo`
    n = [npoints if i == icoo else 10 for i in range(NCOO)]
    n1, n2, n3 = n
    x1, w1 = hermgauss(n1)
    x2, w2 = hermgauss(n2)
    x3, w3 = hermgauss(n3)
    w1 /= np.exp(-(x1**2))
    w2 /= np.exp(-(x2**2))
    w3 /= np.exp(-(x3**2))
    list_x = (x1, x2, x3)
    list_w = (w1, w2, w3)

    # solve for basis functions for the `icoo` vibrational coordinate
    e, v, *_ = vibrations_xy2(
        list_psi,
        list_x,
        list_w,
        list_q,
        select_points=lambda x, w: True,
        select_quanta=lambda q: np.sum(q * np.array([1, 1, 1])) <= nmax,
        x_to_r_map=x_to_r_map,
        gmat=lambda x: batch_Gmat(x),
        pseudo=batch_pseudo,
        potential=potential,
    )

    # keep eigenvectors
    contr_vec.append(v)

    print(f"energies:")
    print(e[0], e - e[0])


Solve for coordinate #0
energies:
3337.3945251424393 [0.00000000e+00 2.62278235e+03 5.15020514e+03 7.58246436e+03
 9.91956242e+03 1.21613549e+04 1.43075890e+04 1.63579482e+04
 1.83123940e+04 2.01753782e+04 2.19804107e+04 2.38279199e+04
 2.58337642e+04 2.80450416e+04 3.04613694e+04 3.30740045e+04
 3.58769744e+04 3.88679012e+04 4.20472946e+04 4.54181980e+04
 4.89859992e+04 5.27577540e+04 5.67453996e+04 6.09584058e+04
 6.54167889e+04 7.01557847e+04 7.51299753e+04 8.05653155e+04
 8.63724076e+04 9.19469603e+04 1.00529194e+05 1.18644018e+05
 1.52570839e+05 2.14310500e+05 3.31561510e+05 5.69151477e+05
 1.08710878e+06 2.31554408e+06 5.58548925e+06 1.63735418e+07]

Solve for coordinate #1
energies:
3337.3945251416912 [0.00000000e+00 2.62278235e+03 5.15020514e+03 7.58246436e+03
 9.91956242e+03 1.21613549e+04 1.43075890e+04 1.63579482e+04
 1.83123940e+04 2.01753782e+04 2.19804107e+04 2.38279199e+04
 2.58337642e+04 2.80450416e+04 3.04613694e+04 3.30740045e+04
 3.58769744e+04 3.88679012e+04 4.2047

Transform primitive basis

In [14]:
# override primitive basis with contracted basis
list_psi = [
    lambda x, n: jnp.dot(hermite(x, n), contr_vec[0]),
    lambda x, n: jnp.dot(hermite(x, n), contr_vec[1]),
    lambda x, n: jnp.dot(hermite(x, n), contr_vec[2]),
]

## Vibrational energies and matrix elements

Using the optimized basis set from the previous step, we solve the vibrational problem employing a polyad basis set truncation.
In this approach, we include only those products of functions in the basis set for which the sum of the corresponding quanta, weighted by specific factors,
is less than or equal to a certain maximum value.
Specifically, we include basis functions that satisfy the condition $2n_1+2n_2+n_3\leq P_\text{max}$, where $n_1$, $n_2$, and $n_3$ are the quantum numbers for the two stretching and one bending coordinates, respectively.

In [15]:
# polyad number for basis set truncation
pmax = 20

# quanta
list_q = [np.arange(nmax) for i in range(NCOO)]

# quadratures
n = [npoints for i in range(NCOO)]
n1, n2, n3 = n
x1, w1 = hermgauss(n1)
x2, w2 = hermgauss(n2)
x3, w3 = hermgauss(n3)
w1 /= np.exp(-(x1**2))
w2 /= np.exp(-(x2**2))
w3 /= np.exp(-(x3**2))
list_x = (x1, x2, x3)
list_w = (w1, w2, w3)

# solutions, including vibrational matrix elements of rotational part of kinetic energy operator
vib_enr, vib_vec, vib_sym, vib_quanta, grot_me, gcor_me, ext_oper_me = vibrations_xy2(
    list_psi,
    list_x,
    list_w,
    list_q,
    select_points=lambda x, w: True,
    select_quanta=lambda q: np.sum(q * np.array([2, 2, 1])) <= pmax,
    x_to_r_map=x_to_r_map,
    gmat=lambda x: batch_Gmat(x),
    pseudo=batch_pseudo,
    potential=potential,
    assign_c2v=True,  # assign symmetries to vibrational states
    ext_oper_list=[spinrot_const_bisector],  # spin-rotation tensor
)

Print vibrational energies with asssignments

In [16]:
nbas_vib = vib_vec.shape[-1]
print("number of vibrational states:", nbas_vib)

ind = np.argmax(np.abs(vib_vec), axis=0)
# add vibrational state symmetry to the vibrational quanta assignment
vib_quanta_j0 = np.concatenate((vib_quanta[ind], np.array(vib_sym)[:, None]), axis=1)
zpe = vib_enr[0]

for e, q in zip(vib_enr, vib_quanta_j0):
    print(e - zpe, q)

number of vibrational states: 506
0.0 ['0' '0' '0' 'A1']
1182.5695896006414 ['0' '0' '1' 'A1']
2353.9073088766704 ['0' '0' '2' 'A1']
2614.394866827381 ['1' '0' '0' 'A1']
2628.4633278424367 ['0' '1' '0' 'B2']
3513.705049529291 ['0' '0' '3' 'A1']
3779.1894940842135 ['1' '0' '1' 'A1']
3789.2699680649735 ['0' '1' '1' 'B2']
4661.605915283004 ['0' '0' '4' 'A1']
4932.68958994003 ['0' '1' '2' 'A1']
4939.130339236135 ['1' '0' '2' 'B2']
5145.0325080259245 ['2' '0' '0' 'A1']
5147.16722639663 ['0' '2' '0' 'B2']
5243.159164558614 ['1' '1' '0' 'A1']
5797.207682793023 ['0' '0' '5' 'A1']
6074.566899182262 ['1' '0' '3' 'A1']
6077.62728540151 ['0' '1' '3' 'B2']
6288.136259845905 ['2' '0' '1' 'A1']
6289.129795754327 ['0' '2' '1' 'B2']
6385.321551894391 ['1' '1' '1' 'A1']
6920.081854231556 ['0' '0' '6' 'A1']
7204.3099529200335 ['1' '0' '4' 'B2']
7204.437296445947 ['0' '1' '4' 'A1']
7419.8516538955355 ['2' '0' '2' 'A1']
7420.081813130413 ['0' '2' '2' 'B2']
7516.827921278722 ['1' '1' '2' 'A1']
7576.41581430

## Rotational basis and matrix elements

For a selected $J$ quantum number of the rotational angular momentum, compute matrix elements $\lang J',k',\tau'|J,k,\tau \rang$, $\lang J',k',\tau'|\hat{J}_\alpha\hat{J}_\beta|J,k,\tau \rang$, and $\lang J',k',\tau'|\hat{J}_\alpha|J,k,\tau \rang$ ($\alpha,\beta=x,y,z$). Where $|J,k,\tau\rang$ are symmetric-top functions in Wang's (symmetry-adapted) representation, $k=0..J$ and $\tau=0,1$ (parity).

In [11]:
j_angmom = 10

# matrix elements <jk'|jk>
s_rot, _, jktau_quanta = rotme_ovlp(j_angmom)

# matrix elements <jk'|Ja*Jb|jk>
jab_rot, *_ = rotme_rot(j_angmom)

# matrix elements <jk'|i*Ja|jk>
ja_rot, *_ = rotme_cor(j_angmom)

nbas_rot = len(jktau_quanta)

print("rotational angular momentum:", j_angmom)
print("number of rotational states:", nbas_rot)

rotational angular momentum: 10
number of rotational states: 21


## Symmetry-adapted rovibrational basis and solutions

In [12]:
# combine vibrational and rotational quanta [(v1, v2, v3, vib_sym, j, k, tau, rot_sym), ...]
rovib_quanta = np.concatenate(
    (
        vib_quanta_j0[:, None, :].repeat(nbas_rot, axis=1),
        jktau_quanta[None, :, :].repeat(nbas_vib, axis=0),
    ),
    axis=-1,
).reshape(-1, 8)

# mapping between rovibrational state index and indices of vibrational and rotational functions
rovib_ind = np.concatenate(
    (
        np.arange(nbas_vib)[:, None, None].repeat(nbas_rot, axis=1),
        np.arange(nbas_rot)[None, :, None].repeat(nbas_vib, axis=0),
    ),
    axis=-1,
).reshape(-1, 2)

# symmetry of rovibrational product prod_sym = vib_sym * rot_sym
prod_sym = np.array(
    [c2v.C2V_PRODUCT_TABLE[(sym1, sym2)] for (sym1, sym2) in rovib_quanta[:, (3, 7)]]
)
# update rovibrational quanta [(j, prod_sym, v1, v2, v3, vib_sym, k, tau, rot_sym), ...]
rovib_quanta = np.concatenate(
    (prod_sym[:, None], rovib_quanta[:, (4, 0, 1, 2, 3, 5, 6, 7)]), axis=-1
)

# identify indices of rovibrational product states for each symmetry
ind_sym = {sym: np.where(rovib_quanta[:, 0] == sym)[0] for sym in c2v.C2V_IRREPS}

# ... indices of vibrational and rotational product states for each symmetry
rovib_ind_sym = {sym: rovib_ind[ind] for sym, ind in ind_sym.items()}

Compute and diagonalise total Hamiltonian matrix for different symmetries

In [13]:
for sym, ind in ind_sym.items():
    vind, rind = rovib_ind[ind].T

    rot_me = jnp.einsum(
        "ijab,ijab->ij", grot_me[np.ix_(vind, vind)], jab_rot[np.ix_(rind, rind)]
    )
    cor_me = jnp.einsum(
        "ija,ija->ij", gcor_me[np.ix_(vind, vind)], ja_rot[np.ix_(rind, rind)]
    )
    vib_me = jnp.diag(vib_enr[vind]) * s_rot[np.ix_(rind, rind)]
    hmat = vib_me + 0.5 * (rot_me + cor_me)

    enr, vec = jnp.linalg.eigh(hmat)
    qua = rovib_quanta[ind[jnp.argmax(vec, axis=0)]]
    for e, q in zip(enr[:20], qua[:20]):
        print(e-zpe, q)

568.4784981609359 ['A1' '10' '0' '0' '0' 'A1' '0' '0' 'A1']
742.854554348226 ['A1' '10' '0' '0' '0' 'A1' '4' '0' 'A1']
875.6311613528337 ['A1' '10' '0' '0' '0' 'A1' '8' '0' 'A1']
960.9040112197222 ['A1' '10' '0' '0' '0' 'A1' '8' '0' 'A1']
1013.3355724363805 ['A1' '10' '0' '0' '0' 'A1' '8' '0' 'A1']
1094.4831270681884 ['A1' '10' '0' '0' '1' 'A1' '6' '0' 'A1']
1747.734809209382 ['A1' '10' '0' '0' '1' 'A1' '0' '0' 'A1']
1933.9995894749704 ['A1' '10' '0' '0' '1' 'A1' '4' '0' 'A1']
2075.222851273262 ['A1' '10' '0' '0' '1' 'A1' '0' '0' 'A1']
2164.8682922650464 ['A1' '10' '0' '0' '1' 'A1' '8' '0' 'A1']
2222.002868282462 ['A1' '10' '0' '0' '1' 'A1' '8' '0' 'A1']
2310.048101449432 ['A1' '10' '0' '0' '2' 'A1' '10' '0' 'A1']
2916.006416130695 ['A1' '10' '0' '0' '2' 'A1' '2' '0' 'A1']
3114.8593291627944 ['A1' '10' '0' '0' '2' 'A1' '6' '0' 'A1']
3174.4069972405055 ['A1' '10' '1' '0' '0' 'A1' '2' '0' 'A1']
3190.173269944627 ['A1' '10' '0' '1' '0' 'B2' '1' '0' 'B2']
3264.8890492822134 ['A1' '10' '0' 

## Run rovibrational calculations for $J=0..J_\text{max}$

Put three previous cells into one and add a loop over $J$.

In [14]:
import gzip
import h5py

max_j = 60
max_energy = 40000

# store energies below `max_energy` in text file
fl_enr = gzip.open(f"h2s_energies_pmax{pmax}_jmax{max_j}.txt.gz", "wt")

for j_angmom in range(0, max_j + 1):

    # store energies and wavefunctions in hdf5 file
    h5 = h5py.File(f"h2s_coefficients_pmax{pmax}_j{j_angmom}.h5", "w")
    h5_enr = h5.create_group("energies")
    h5_coef = h5.create_group("coefficients")
    h5_qua = h5.create_group("quanta")

    s_rot, _, ktau_quanta = rotme_ovlp(j_angmom)
    jab_rot, *_ = rotme_rot(j_angmom)
    ja_rot, *_ = rotme_cor(j_angmom)
    nbas_rot = len(ktau_quanta)

    print("solve for rotational angular momentum:", j_angmom)

    rovib_quanta = np.concatenate(
        (
            vib_quanta_j0[:, None, :].repeat(nbas_rot, axis=1),
            ktau_quanta[None, :, :].repeat(nbas_vib, axis=0),
        ),
        axis=-1,
    ).reshape(-1, 8)

    rovib_ind = np.concatenate(
        (
            np.arange(nbas_vib)[:, None, None].repeat(nbas_rot, axis=1),
            np.arange(nbas_rot)[None, :, None].repeat(nbas_vib, axis=0),
        ),
        axis=-1,
    ).reshape(-1, 2)

    prod_sym = np.array(
        [
            c2v.C2V_PRODUCT_TABLE[(sym1, sym2)]
            for (sym1, sym2) in rovib_quanta[:, (3, 7)]
        ]
    )
    rovib_quanta = np.concatenate(
        (prod_sym[:, None], rovib_quanta[:, (4, 0, 1, 2, 3, 5, 6, 7)]), axis=-1
    )

    ind_sym = {sym: np.where(rovib_quanta[:, 0] == sym)[0] for sym in c2v.C2V_IRREPS}
    # rovib_ind_sym = {sym: rovib_ind[ind] for sym, ind in ind_sym.items()}

    for sym, ind in ind_sym.items():
        vind, rind = rovib_ind[ind].T
        qua = rovib_quanta[ind]

        rot_me = jnp.einsum(
            "ijab,ijab->ij", grot_me[np.ix_(vind, vind)], jab_rot[np.ix_(rind, rind)]
        )
        cor_me = jnp.einsum(
            "ija,ija->ij", gcor_me[np.ix_(vind, vind)], ja_rot[np.ix_(rind, rind)]
        )
        vib_me = jnp.diag(vib_enr[vind]) * s_rot[np.ix_(rind, rind)]
        hmat = vib_me + 0.5 * (rot_me + cor_me)
        enr, vec = jnp.linalg.eigh(hmat)

        if len(vec) == 0:  # no A2 and B1 states for J=0
            continue

        # store data in hdf5 file
        enr_ind = np.where(enr - zpe < max_energy)[0]
        h5_enr.create_dataset(sym, data=enr[enr_ind])
        h5_coef.create_dataset(sym, data=vec[:, enr_ind])
        qua_str = [",".join(elem) for elem in qua]
        max_len = max([len(elem) for elem in qua_str])
        qua_ascii = [elem.encode("ascii", "ignore") for elem in qua_str]
        h5_qua.create_dataset(sym, (len(qua_ascii), 1), f"S{max_len}", data=qua_ascii)

        qua = rovib_quanta[ind[jnp.argmax(vec, axis=0)]]

        # store energies and assignments in text file
        for e, q in zip(enr, qua):
            e_ = e - zpe
            if e_ < max_energy:
                fl_enr.write(
                    f"{e_:18.6f}    " + " ".join(f"{elem:4s}" for elem in q) + "\n"
                )

    h5.close()

fl_enr.close()

solve for rotational angular momentum: 0
solve for rotational angular momentum: 1
solve for rotational angular momentum: 2
solve for rotational angular momentum: 3
solve for rotational angular momentum: 4
solve for rotational angular momentum: 5
solve for rotational angular momentum: 6
solve for rotational angular momentum: 7
solve for rotational angular momentum: 8
solve for rotational angular momentum: 9
solve for rotational angular momentum: 10
solve for rotational angular momentum: 11
solve for rotational angular momentum: 12
solve for rotational angular momentum: 13
solve for rotational angular momentum: 14
solve for rotational angular momentum: 15
solve for rotational angular momentum: 16
solve for rotational angular momentum: 17
solve for rotational angular momentum: 18
solve for rotational angular momentum: 19
solve for rotational angular momentum: 20
solve for rotational angular momentum: 21
solve for rotational angular momentum: 22
solve for rotational angular momentum: 23
so

Compare calculated rovibrational energies with results of DVR3D calculations, published in [Azzam, A. A. A., Tennyson, J., Yurchenko, S. N., Naumenko, O. V., "ExoMol molecular line lists – XVI: The rotation-vibration spectrum of hot H2S", Monthly Notices of the Royal Astronomical Society 460, 4063-4074 (2016)](https://doi.org/10.1093/mnras/stw1133). The reference data is stored in file 'etc/benchmark/1H2-32S__AYT2_20191004.states.bz2', for further details, see the 'etc/benchmark/README.md'.

In [15]:
import bz2
import gzip

max_energy = 10000
max_j = 20

# read reference energies
ref_enr = {}
with bz2.open("etc/benchmark/1H2-32S__AYT2_20191004.states.bz2", "rt") as fl:
    for line in fl:
        w = line.split()
        e = float(w[1])
        j = int(w[3])
        sym = w[5]
        if e > max_energy or j > max_j:
            continue
        try:
            ref_enr[(j, sym)].append(e)
        except KeyError:
            ref_enr[(j, sym)] = [e]
ref_enr = {j: sorted(e) for j, e in ref_enr.items()}

# read calculated energies
cal_enr = {}
with gzip.open(f"h2s_energies_pmax{pmax}_jmax60.txt.gz", "rt") as fl:
    for line in fl:
        w = line.split()
        e = float(w[0])
        j = int(w[2])
        sym = w[1]
        if e > max_energy or j > max_j:
            continue
        try:
            cal_enr[(j, sym)].append(e)
        except KeyError:
            cal_enr[(j, sym)] = [e]
cal_enr = {j: sorted(e) for j, e in cal_enr.items()}

print("max and mean differences between the calculated and reference energies")
for j, sym in cal_enr.keys():
    diff = np.array(cal_enr[(j, sym)]) - np.array(ref_enr[(j, sym)])
    max_diff = np.max(np.abs(diff))
    mean_diff = np.mean(np.abs(diff))
    print(f"j = {j}  sym = {sym}  no_states = {len(diff)}  max_diff = {max_diff}  mean_diff = {mean_diff}")

max and mean differences between the calculated and reference energies
j = 0  sym = A1  no_states = 33  max_diff = 0.012713000000076136  mean_diff = 0.0026534242425496454
j = 0  sym = B2  no_states = 18  max_diff = 0.013872999999875901  mean_diff = 0.0035352777777764763
j = 1  sym = A1  no_states = 18  max_diff = 0.01377899999897636  mean_diff = 0.003511277777710752
j = 1  sym = A2  no_states = 50  max_diff = 0.013707000000067637  mean_diff = 0.002838420000143849
j = 1  sym = B1  no_states = 50  max_diff = 0.013713000000279862  mean_diff = 0.002839539999972658
j = 1  sym = B2  no_states = 32  max_diff = 0.012622000000192202  mean_diff = 0.0024491874998312513
j = 2  sym = A1  no_states = 82  max_diff = 0.013348000000405591  mean_diff = 0.0026629634145533447
j = 2  sym = A2  no_states = 50  max_diff = 0.013548000000810134  mean_diff = 0.002801879999976933
j = 2  sym = B1  no_states = 50  max_diff = 0.013512000001355773  mean_diff = 0.0027982600000316894
j = 2  sym = B2  no_states = 68  m